name: github pages
on:
  workflow_dispatch:
  push:
    branches:
      - master # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build:website
      - run: npm run website